config/routes.rb
Rails.application.routes.draw do

  resources :courses, only: [:new, :index, :create, :show] do 
    resources :reviews, except: [:index]
  end

  resources :languages, only: [:index, :show]

  resources :authors, only: [:index, :show]

  resources :users, only: [:index, :show, :home]

  root 'users#home'

  get '/signup' => "users#new"
  post '/users' => "users#create"
  get '/login' => "sessions#new"
  post '/login' => "sessions#create"
  post '/logout' => "sessions#destroy"

  get '/auth/facebook/callback' => 'sessions#create'
 
end

app/models/language.rb
class Language < ApplicationRecord
  has_many :courses
  has_many :authors, through: :courses
  validates :name, presence: true, :uniqueness => {message: "The Language you entered has already been added to the site, please select it from the dropdown menu!"}

  scope :most_courses, -> {joins(:courses).group(:language_id).order("COUNT(courses.language_id) DESC").limit(10)}

  def self.search(search)
    if search
      self.where('name LIKE ?', "%#{search}%")
    else 
      Language.most_courses
    end
  end
end

app/controllers/languages_controller.rb
class LanguagesController < ApplicationController

  before_action :require_login


  def index
    if params[:search] != "" 
        @languages = Language.search(params[:search]) 
    else
        @languages = Language.most_courses
    end
  end

  def show 
    @language = Language.find(params[:id])
    @courses = @language.courses
  end

end

app/helpers/languages_helper.rb
module LanguagesHelper
end

app/views/languages/index.html.erb
<div class="displayContainer">
<h1>Click on a Language to see its Courses!</h1><br>

<%= form_tag(languages_path, method: :get) do %>
        <%= text_field_tag(:search, params[:search]) %>
        <%= submit_tag ("Search") %> 
    <% end %>
<br>
<% @languages.each do |language| %>
<h2><%= link_to "#{language.name}", language_path(language) %></h2>
<p><%= language.courses.count %> Course(s)</p>
<% end %>


</div>

app/views/languages/show.html.erb
<div class="displayContainer">

<h1>Courses to learn <%= @language.name%></h1>
<h2>Click on a course to see its reviews!</h2>

<% @courses.each do |c|%>
<h3><%= link_to "#{c.title}", course_path(c) %></h3>
<p>Author/Publisher: <%= c.author.name %></p>
<p>Level: <%= c.level %></p>
<p><%= c.reviews.count %> Review(s)</p>
<%end %>

</div>