config/routes.rb
Rails.application.routes.draw do

  resources :courses, only: [:new, :index, :create, :show] do 
    resources :reviews, except: [:index]
  end

  resources :languages, only: [:index, :show]

  resources :authors, only: [:index, :show]

  resources :users, only: [:index, :show, :home]

  root 'users#home'

  get '/signup' => "users#new"
  post '/users' => "users#create"
  get '/login' => "sessions#new"
  post '/login' => "sessions#create"
  post '/logout' => "sessions#destroy"

  get '/auth/facebook/callback' => 'sessions#create'
 
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :courses
  has_many :languages
  validates :name, presence: true, :uniqueness => {message: "The Author/Publisher you entered has already been added to the site, please select it from the dropdown menu!"}

  scope :most_courses, -> {joins(:courses).group(:author_id).order("COUNT(courses.author_id) DESC").limit(10)}

  def self.search(search)
    if search
      self.where('name LIKE ?', "%#{search}%")
    else 
      Author.most_courses
    end
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController

  before_action :require_login

  def index
    if params[:search] != ""
        @authors = Author.search(params[:search]) 
    else
        @authors = Author.most_courses
    end
  end

  def show 
      @author = Author.find(params[:id])
      @courses = @author.courses
  end

end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/views/authors/index.html.erb
<div class="displayContainer">
<h1>Click on an Author/Publisher to see more details about their courses!</h1><br>

<%= form_tag(authors_path, method: :get) do %>
        <%= text_field_tag(:search, params[:search]) %>
        <%= submit_tag ("Search") %> 
    <% end %>
<br>
<% @authors.each do |author| %>
<h2><%= link_to "#{author.name}", author_path(author) %></h2>
<p><%= author.courses.count %> Course(s)</p>
<% end %>



</div>

app/views/authors/show.html.erb
<div class="displayContainer">
<h1>Click on a Course to see its reviews!</h1>

<h2><%= @author.name %>'s Courses:</h2>

<% @courses.each do |course| %>
<h2><%= link_to "#{course.title}", course_path(course) %></h2>
<p><%= course.language.name %></p>
<p><%= course.level %></p>
<p><%= course.reviews.count%> Review(s)</p>
<% end %>



</div>