config/routes.rb
Rails.application.routes.draw do

  resources :courses, only: [:new, :index, :create, :show] do 
    resources :reviews, except: [:index]
  end

  resources :languages, only: [:index, :show]

  resources :authors, only: [:index, :show]

  resources :users, only: [:index, :show, :home]

  root 'users#home'

  get '/signup' => "users#new"
  post '/users' => "users#create"
  get '/login' => "sessions#new"
  post '/login' => "sessions#create"
  post '/logout' => "sessions#destroy"

  get '/auth/facebook/callback' => 'sessions#create'
 
end

app/models/user.rb
class User < ApplicationRecord
  has_many :reviews
  has_many :courses, through: :reviews
  has_many :authors, through: :courses
  has_many :languages, through: :courses
  validates :name, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true


  has_secure_password

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :require_login, except: [:home, :new, :create]

  def home 
      if !session[:user_id]
        @user = User.new 
      else  
        @user = User.find(session[:user_id])
        redirect_to user_path(@user)
      end
  end

  def new 
    if !session[:user_id]
      @user = User.new 
    else  
      @user = User.find(session[:user_id])
      redirect_to user_path(@user)
    end
  end

  def create 
    @user = User.new(user_params)
    if @user.save 
      session[:user_id] = @user.id 
      redirect_to user_path(@user)
    else 
      render '/users/home'
    end
  end

  def show
    @user = User.find(params[:id])
    @reviews = @user.reviews
  end

  private 

  def user_params 
    params.require(:user).permit(:name, :password, :password_confirmation, :email)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/home.html.erb
<div class="container">
<div class="heading">
<h1>LingoRater</h1></div>
<div class="openApp">

<% if @user.errors.any? %>
		<ul>
    <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
    <% end %>
    </ul>
<% end %>
<br>

<h1>Sign Up</h1>

  <%=form_for @user do |f|%>
    <%=f.label "Username:"%><br>
    <%=f.text_field :name%><br>
    <%=f.label "Email:"%><br>
    <%=f.text_field :email%><br>
    <%=f.label "Password:"%><br>
    <%=f.password_field :password%><br>
    <%=f.label :password_confirmation, "Confirm Password:"%><br>
    <%=f.password_field :password_confirmation%><br><br>
    <%=f.submit "Sign Up"%>
  <%end%>
<br>

<h1>Log In</h1>
<%= form_for(:session, url: login_path) do |f| %>
<%=f.label "Username:"%><br>
<%=f.text_field :name%><br>
<%=f.label "Password:"%><br>
<%=f.password_field :password %><br><br>
<%= f.submit "Log In"%><br><br>
<% end %>

<%# Need to add links here to other Oauth logins %>
<div class="fbLogin">
<%= link_to('Log in with Facebook', '/auth/facebook', class: "fbBtn") %>
<i class="fab fa-facebook-square"></i>
</div>
</div>


</div>

app/views/users/show.html.erb
<div class="displayContainer">

<h1>Welcome to LingoRater, <%= @user.name %>!</h1>
<br>
<p>To start making use of our site, check out the navigation bar above. Here you can create a new course review or search for already existing reviews. You can search by title, author/publisher or by language.</p>
<br>
<p>Here at LingoRater, our focus is on having as many high quality reviews for as many courses as possible. In order to adhere to these high standards, we have a few sitewide rules:</p>
<br>
<ul class="rulesList">
<li>1. Please search through our site first to see if your course has been created. This way users will be able to find all the reviews for a particular course on one handy page!</li><br>
<li>2. Try to provide as much information about a new course as possible if you are the first user to add it to our site!</li><br>
<li>3. Please make your reviews as detailed as you can, we have a minimum character count for the reviews as we do not wish any course page to fill up with small unhelpful reviews.</li>
</ul>
<br>

<p>If at any time you wish to read the instructions/rules for the app, click your name in the navigation bar at the top of the screen and you will be brought back to this page.</p>
<br>
<h3>Happy LingoRating!!!</h3>

</div>