config/routes.rb
Rails.application.routes.draw do

  resources :courses, only: [:new, :index, :create, :show] do 
    resources :reviews, except: [:index]
  end

  resources :languages, only: [:index, :show]

  resources :authors, only: [:index, :show]

  resources :users, only: [:index, :show, :home]

  root 'users#home'

  get '/signup' => "users#new"
  post '/users' => "users#create"
  get '/login' => "sessions#new"
  post '/login' => "sessions#create"
  post '/logout' => "sessions#destroy"

  get '/auth/facebook/callback' => 'sessions#create'
 
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LingoRater</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  
  </head>

  <body>
   <%if logged_in?%>
    <nav>
    <h1>LingoRater</h1>
     
      <div class="navElements">
      <%=link_to "#{current_user_username}", user_path(current_user)%></>
      <%=link_to "Create Review", new_course_path%></>
      <%=link_to "Courses", courses_path%></>
      <%=link_to "Publishers", authors_path%></>
      <%=link_to "Languages", languages_path%></>
      <%=link_to "Log Out", logout_path, method:'post', action:'destroy'%></>
      </div>
    </nav>
    <%end %>
    <%= yield %>
    <script src="https://kit.fontawesome.com/7e5d4c6769.js" crossorigin="anonymous"></script>
  </body>
</html>